import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import "../styles/table.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import 'swiper/css';
import 'swiper/css/pagination';

import { ThemeProvider } from '@/components/common/themeProvider/ThemePrivider';
import ReduxProvider from '@/store/provider';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dana = localFont({
  src : [
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Hairline.woff2' ,
          weight : '10' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Thin.woff2' ,
          weight : '100' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-UltraLight.woff2' ,
          weight : '200' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Light.woff2' ,
          weight : '300' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Regular.woff2' ,
          weight : '400' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Medium.woff2' ,
          weight : '500' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-DemiBold.woff2' ,
          weight : '600' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-ExtraBold.woff2' ,
          weight : '700' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-Black.woff2' ,
          weight : '800' ,
          style : 'normal'
      },
      {
          path : './../../public/fonts/dana/woff2/DanaFaNum-ExtraBold.woff2' ,
          weight : '900' ,
          style : 'normal'
      },
   
  ]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" suppressHydrationWarning>
      <body dir="rtl" className={`bg-bg-100 dark:bg-bgDark-100 flex flex-col ${dana.className} h-screen box-border overflow-y-auto`}>
        <ThemeProvider defaultTheme="light" attribute='class'>
          <ReduxProvider>
            <ToastContainer
            className={`${dana.className}`}
            position="top-right"
            autoClose={6000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={true}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
